version: '3.4'
services:
  web-api:
    build:
      context: .
      dockerfile: HardwareShop.WebApi/Dockerfile.dev
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ASPNETCORE_ENVIRONMENT=DevContainer
    ports:
      - 5000:5000