version: "3.8"
services:
  kafka-consumer:
    build:
      context: .
      dockerfile: HardwareShop.KafkaConsumer/Dockerfile.dev
    depends_on:
      - broker
    networks:
      - api-shop

