version: "3.8"
services:
  migration:
    build:
      context: .
      dockerfile: HardwareShop.DatabaseMigration/Dockerfile.dev
    networks:
      - api-shop

  web-api:
    deploy:
      replicas: 0

